// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjFL0nAQiua27PyjkLJJhBbaipoMhbW9w',
    appId: '1:2987109270:web:c2177fd41fe225ebb54bb7',
    messagingSenderId: '2987109270',
    projectId: 'f1-77381',
    authDomain: 'f1-77381.firebaseapp.com',
    storageBucket: 'f1-77381.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT9eDWFAAG6OOp4RKkyRdAx3xxabe-jRw',
    appId: '1:2987109270:android:987cde5ec299f2cbb54bb7',
    messagingSenderId: '2987109270',
    projectId: 'f1-77381',
    storageBucket: 'f1-77381.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYtN0omblXAuwWWuotoeCPT2-OTsmETAA',
    appId: '1:2987109270:ios:927a66452c8a1110b54bb7',
    messagingSenderId: '2987109270',
    projectId: 'f1-77381',
    storageBucket: 'f1-77381.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );
}
